#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Anujin-crs 
# SPDX-License-Identifier: BSD-3-Clause

import sys

def tonum(s):
    try:
        return int(s)
    except:
        return float(s)


ans = 0
n = 0

for line in sys.stdin:
    line = line.rstrip()
    ans += tonum(line)
    n += 1

avg = ans / n


if avg >= 90 and avg <= 100:
    print("Grade", f"{'Mark' : ^10}")
    print(avg, f"{'S' : ^10}")
elif avg >= 80 and avg < 90:
    print("Grade", f"{'Mark' : ^10}")
    print(avg, f"{'A' : ^10}")
elif avg >= 70 and avg < 80:
    print("Grade", f"{'Mark' : ^10}")
    print(avg, f"{'B' : ^10}")
elif avg >= 60 and avg < 70:
    print("Grade", f"{'Mark' : ^10}")
    print(avg, f"{'C' : ^10}")
elif avg < 60:
    print("Grade", f"{'Mark' : ^10}")
    print(avg, f"{'Failed' : ^15}")
else:
    print("Invalid Input!")


